name: 'Docker-Kubectl-Helm'
author: 'Junv'
description: 'A Github action for using docker, kubectl and helm to deploy applications to Kubernetes cluster'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'truck'
  color: 'blue'
